{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Load and resize images"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# train_labels = pd.read_csv('../data/train-lables.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file \"/home/ubuntu/.config/matplotlib/matplotlibrc\", line #2\n",
      "  (fname, cnt))\n",
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file \"/home/ubuntu/.config/matplotlib/matplotlibrc\", line #3\n",
      "  (fname, cnt))\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "validation_labels = pd.read_csv('../data/validation-lables.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from skimage.io import imread\n",
    "from skimage.transform import resize\n",
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def load_images(input_dir, size):\n",
    "    filenames = os.listdir(input_dir)\n",
    "    \n",
    "    result = []\n",
    "    \n",
    "    for filename in filenames:\n",
    "        image_name = filename.split('.')[0]\n",
    "        image_id = image_name.split('_')[1]\n",
    "        try:\n",
    "            image = imread(os.path.join(input_dir, filename))\n",
    "            if len(image.shape) != 3 and image.shape[2] == 3:\n",
    "                raise 'Bad image dimensions'\n",
    "            result.append([image_id, resize(image, size)])\n",
    "        except Exception as e:\n",
    "            print(e)\n",
    "            print(image_name.split('_')[1])\n",
    "            \n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.\n",
      "  warn(\"The default mode, 'constant', will be changed to 'reflect' in \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3015.png'>\n",
      "3015\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_6102.png'>\n",
      "6102\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4456.png'>\n",
      "4456\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3023.png'>\n",
      "3023\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5992.png'>\n",
      "5992\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5675.png'>\n",
      "5675\n",
      "tuple index out of range\n",
      "5387\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2902.png'>\n",
      "2902\n",
      "tuple index out of range\n",
      "178\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4753.png'>\n",
      "4753\n",
      "tuple index out of range\n",
      "4774\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3733.png'>\n",
      "3733\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5737.png'>\n",
      "5737\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_157.png'>\n",
      "157\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 19398656 bytes but only got 0. Skipping tag 0\n",
      "  \" Skipping tag %s\" % (size, len(data), tag))\n",
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 19988480 bytes but only got 0. Skipping tag 0\n",
      "  \" Skipping tag %s\" % (size, len(data), tag))\n",
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 40108032 bytes but only got 0. Skipping tag 0\n",
      "  \" Skipping tag %s\" % (size, len(data), tag))\n",
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 34865152 bytes but only got 0. Skipping tag 0\n",
      "  \" Skipping tag %s\" % (size, len(data), tag))\n",
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 10. \n",
      "  warnings.warn(str(msg))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_61.png'>\n",
      "61\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4160.png'>\n",
      "4160\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_6146.png'>\n",
      "6146\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_972.png'>\n",
      "972\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1434.png'>\n",
      "1434\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1198.png'>\n",
      "1198\n",
      "tuple index out of range\n",
      "5573\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3324.png'>\n",
      "3324\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "3330\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4680.png'>\n",
      "4680\n",
      "tuple index out of range\n",
      "2254\n",
      "tuple index out of range\n",
      "693\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4140.png'>\n",
      "4140\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4752.png'>\n",
      "4752\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5861.png'>\n",
      "5861\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_624.png'>\n",
      "624\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5524.png'>\n",
      "5524\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3971.png'>\n",
      "3971\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1065.png'>\n",
      "1065\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4604.png'>\n",
      "4604\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "2147\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2039.png'>\n",
      "2039\n",
      "tuple index out of range\n",
      "4299\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (95 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "1268\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3535.png'>\n",
      "3535\n",
      "tuple index out of range\n",
      "4372\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (2 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "5359\n",
      "tuple index out of range\n",
      "2782\n",
      "tuple index out of range\n",
      "3591\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (19 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "5069\n",
      "tuple index out of range\n",
      "513\n",
      "tuple index out of range\n",
      "4905\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5878.png'>\n",
      "5878\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1463.png'>\n",
      "1463\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4291.png'>\n",
      "4291\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5178.png'>\n",
      "5178\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "671\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5347.png'>\n",
      "5347\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "261\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1133.png'>\n",
      "1133\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2424.png'>\n",
      "2424\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "2050\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1629.png'>\n",
      "1629\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1990.png'>\n",
      "1990\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1299.png'>\n",
      "1299\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2031.png'>\n",
      "2031\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "6381\n",
      "tuple index out of range\n",
      "3630\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_6192.png'>\n",
      "6192\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3445.png'>\n",
      "3445\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_120.png'>\n",
      "120\n",
      "tuple index out of range\n",
      "2200\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5444.png'>\n",
      "5444\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2099.png'>\n",
      "2099\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3638.png'>\n",
      "3638\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1956.png'>\n",
      "1956\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4389.png'>\n",
      "4389\n",
      "tuple index out of range\n",
      "3599\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1127.png'>\n",
      "1127\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1522.png'>\n",
      "1522\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1136.png'>\n",
      "1136\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_722.png'>\n",
      "722\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_6294.png'>\n",
      "6294\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2807.png'>\n",
      "2807\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3724.png'>\n",
      "3724\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_6215.png'>\n",
      "6215\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "2899\n",
      "tuple index out of range\n",
      "3285\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2354.png'>\n",
      "2354\n",
      "tuple index out of range\n",
      "2515\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "4657\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_4330.png'>\n",
      "4330\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1770.png'>\n",
      "1770\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2469.png'>\n",
      "2469\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_3372.png'>\n",
      "3372\n",
      "tuple index out of range\n",
      "6318\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1902.png'>\n",
      "1902\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "1410\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2792.png'>\n",
      "2792\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_5586.png'>\n",
      "5586\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_140.png'>\n",
      "140\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1520.png'>\n",
      "1520\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_807.png'>\n",
      "807\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2292.png'>\n",
      "2292\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_2072.png'>\n",
      "2072\n",
      "cannot identify image file <_io.BufferedReader name='../data/validation/pic_1860.png'>\n",
      "1860\n"
     ]
    }
   ],
   "source": [
    "val_images = load_images('../data/validation/', (299, 299))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(5873, 299, 299, 3)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x_data = np.array([image[1] for image in val_images if image[1].shape[2] == 3])\n",
    "x_data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "validation_image_ids = pd.DataFrame([image[0] for image in val_images if image[1].shape[2] == 3], columns=['val_image_id']) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "validation_image_labels = pd.concat([\n",
    "    validation_image_ids.astype(int).set_index('val_image_id'),\n",
    "    validation_labels.set_index('image_id')], join='inner', axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(5873, 1)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "validation_image_labels_np = validation_image_labels.reset_index(drop=True).as_matrix()\n",
    "validation_image_labels_np.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Define model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "from keras.models import Model\n",
    "from keras.layers import Dense\n",
    "from keras.callbacks import EarlyStopping, ModelCheckpoint\n",
    "from keras.preprocessing import image\n",
    "from keras.applications.inception_v3 import preprocess_input, decode_predictions, InceptionV3\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# load in preprocessed data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# x_data = validation_image_array"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "y_data = validation_image_labels_np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "num_classes = 128\n",
    "\n",
    "model = InceptionV3(weights='imagenet')\n",
    "\n",
    "intermediate_layer_model = Model(inputs=model.input, outputs=model.layers[311].output)\n",
    "\n",
    "x = intermediate_layer_model.output\n",
    "x = Dense(1024, activation='relu')(x)\n",
    "predictions = Dense(num_classes, activation='softmax')(x)\n",
    "\n",
    "transfer_model = Model(inputs=intermediate_layer_model.input, outputs=predictions)\n",
    "\n",
    "# train last cluster and dense layer\n",
    "for layer in transfer_model.layers:\n",
    "    layer.trainable = False\n",
    "\n",
    "# can train more \n",
    "for i in range(311,313):\n",
    "    transfer_model.layers[i].trainable = True\n",
    "\n",
    "transfer_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "# using checkpoints and early stopping on validation sample to prevent overfitting\n",
    "# best weight is saved to file_path\n",
    "file_path=\"../checkpoints/weights_base.best.hdf5\"\n",
    "checkpoint = ModelCheckpoint(file_path, monitor='val_loss', verbose=1, save_best_only=True, mode='min')\n",
    "early = EarlyStopping(monitor=\"val_loss\", mode=\"min\", patience=2)\n",
    "callbacks_list = [checkpoint, early] "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Train model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 5285 samples, validate on 588 samples\n",
      "Epoch 1/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 3.6203 - acc: 0.2275\n",
      "Epoch 00001: val_loss improved from inf to 2.40386, saving model to ../checkpoints/weights_base.best.hdf5\n",
      "5285/5285 [==============================] - 31s 6ms/step - loss: 3.6192 - acc: 0.2278 - val_loss: 2.4039 - val_acc: 0.4235\n",
      "Epoch 2/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 1.9940 - acc: 0.5186\n",
      "Epoch 00002: val_loss improved from 2.40386 to 1.89976, saving model to ../checkpoints/weights_base.best.hdf5\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 1.9938 - acc: 0.5186 - val_loss: 1.8998 - val_acc: 0.4898\n",
      "Epoch 3/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 1.4353 - acc: 0.6244\n",
      "Epoch 00003: val_loss improved from 1.89976 to 1.84647, saving model to ../checkpoints/weights_base.best.hdf5\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 1.4359 - acc: 0.6244 - val_loss: 1.8465 - val_acc: 0.4915\n",
      "Epoch 4/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 1.1536 - acc: 0.6960\n",
      "Epoch 00004: val_loss did not improve\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 1.1541 - acc: 0.6956 - val_loss: 1.9005 - val_acc: 0.4949\n",
      "Epoch 5/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 0.9592 - acc: 0.7413\n",
      "Epoch 00005: val_loss improved from 1.84647 to 1.81260, saving model to ../checkpoints/weights_base.best.hdf5\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 0.9602 - acc: 0.7410 - val_loss: 1.8126 - val_acc: 0.5153\n",
      "Epoch 6/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 0.7852 - acc: 0.7884\n",
      "Epoch 00006: val_loss improved from 1.81260 to 1.81141, saving model to ../checkpoints/weights_base.best.hdf5\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 0.7857 - acc: 0.7885 - val_loss: 1.8114 - val_acc: 0.5119\n",
      "Epoch 7/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 0.6922 - acc: 0.8201\n",
      "Epoch 00007: val_loss did not improve\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 0.6929 - acc: 0.8199 - val_loss: 1.8276 - val_acc: 0.5153\n",
      "Epoch 8/20\n",
      "5280/5285 [============================>.] - ETA: 0s - loss: 0.6015 - acc: 0.8411\n",
      "Epoch 00008: val_loss did not improve\n",
      "5285/5285 [==============================] - 19s 4ms/step - loss: 0.6025 - acc: 0.8411 - val_loss: 1.9846 - val_acc: 0.4915\n"
     ]
    }
   ],
   "source": [
    "epoch = 20\n",
    "\n",
    "# onehot encoding\n",
    "y_onehot = np.zeros((y_data.shape[0], num_classes))\n",
    "for i in range(0,num_classes):\n",
    "    (y_onehot[:,i:i+1])[y_data==i] = 1\n",
    "\n",
    "transfer_model.fit(x_data, y_onehot, epochs=epoch, validation_split=0.1, batch_size=32, callbacks=callbacks_list,verbose=1)\n",
    "\n",
    "# load best weights\n",
    "transfer_model.load_weights(file_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Apply to submission dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.\n",
      "  warn(\"The default mode, 'constant', will be changed to 'reflect' in \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7670.png'>\n",
      "7670\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8711.png'>\n",
      "8711\n",
      "tuple index out of range\n",
      "2326\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (9 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "4559\n",
      "tuple index out of range\n",
      "2361\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7517.png'>\n",
      "7517\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_900.png'>\n",
      "900\n",
      "tuple index out of range\n",
      "5992\n",
      "tuple index out of range\n",
      "3468\n",
      "tuple index out of range\n",
      "1679\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "10195\n",
      "tuple index out of range\n",
      "6619\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4413.png'>\n",
      "4413\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5558.png'>\n",
      "5558\n",
      "tuple index out of range\n",
      "7004\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11624.png'>\n",
      "11624\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11737.png'>\n",
      "11737\n",
      "tuple index out of range\n",
      "6615\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6798.png'>\n",
      "6798\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11701.png'>\n",
      "11701\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1462.png'>\n",
      "1462\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7855.png'>\n",
      "7855\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1544.png'>\n",
      "1544\n",
      "tuple index out of range\n",
      "12152\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12514.png'>\n",
      "12514\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9340.png'>\n",
      "9340\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5346.png'>\n",
      "5346\n",
      "tuple index out of range\n",
      "9047\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1783.png'>\n",
      "1783\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_710.png'>\n",
      "710\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7222.png'>\n",
      "7222\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "11700\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6888.png'>\n",
      "6888\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_444.png'>\n",
      "444\n",
      "tuple index out of range\n",
      "1045\n",
      "tuple index out of range\n",
      "8555\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6873.png'>\n",
      "6873\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2124.png'>\n",
      "2124\n",
      "tuple index out of range\n",
      "7662\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3717.png'>\n",
      "3717\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2300.png'>\n",
      "2300\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10668.png'>\n",
      "10668\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11634.png'>\n",
      "11634\n",
      "tuple index out of range\n",
      "8598\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "2280\n",
      "tuple index out of range\n",
      "798\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12487.png'>\n",
      "12487\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4699.png'>\n",
      "4699\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10534.png'>\n",
      "10534\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8535.png'>\n",
      "8535\n",
      "tuple index out of range\n",
      "9752\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2781.png'>\n",
      "2781\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7968.png'>\n",
      "7968\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11799.png'>\n",
      "11799\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3513.png'>\n",
      "3513\n",
      "tuple index out of range\n",
      "156\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "3334\n",
      "tuple index out of range\n",
      "11053\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11603.png'>\n",
      "11603\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3645.png'>\n",
      "3645\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11875.png'>\n",
      "11875\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11041.png'>\n",
      "11041\n",
      "tuple index out of range\n",
      "6930\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8506.png'>\n",
      "8506\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8161.png'>\n",
      "8161\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10207.png'>\n",
      "10207\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4531.png'>\n",
      "4531\n",
      "tuple index out of range\n",
      "7865\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6189.png'>\n",
      "6189\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7440.png'>\n",
      "7440\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12622.png'>\n",
      "12622\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4515.png'>\n",
      "4515\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8407.png'>\n",
      "8407\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10167.png'>\n",
      "10167\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_716.png'>\n",
      "716\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8538.png'>\n",
      "8538\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5492.png'>\n",
      "5492\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12067.png'>\n",
      "12067\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3042.png'>\n",
      "3042\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7598.png'>\n",
      "7598\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9433.png'>\n",
      "9433\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5709.png'>\n",
      "5709\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7779.png'>\n",
      "7779\n",
      "tuple index out of range\n",
      "7019\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3268.png'>\n",
      "3268\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2181.png'>\n",
      "2181\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6613.png'>\n",
      "6613\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5141.png'>\n",
      "5141\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4598.png'>\n",
      "4598\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9397.png'>\n",
      "9397\n",
      "tuple index out of range\n",
      "6795\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9557.png'>\n",
      "9557\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4656.png'>\n",
      "4656\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "11780\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7972.png'>\n",
      "7972\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "433\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11679.png'>\n",
      "11679\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_320.png'>\n",
      "320\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3245.png'>\n",
      "3245\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1898.png'>\n",
      "1898\n",
      "tuple index out of range\n",
      "10605\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7106.png'>\n",
      "7106\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_489.png'>\n",
      "489\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4888.png'>\n",
      "4888\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2542.png'>\n",
      "2542\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_633.png'>\n",
      "633\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3517.png'>\n",
      "3517\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1997.png'>\n",
      "1997\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_262.png'>\n",
      "262\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7056.png'>\n",
      "7056\n",
      "tuple index out of range\n",
      "6344\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12023.png'>\n",
      "12023\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12280.png'>\n",
      "12280\n",
      "tuple index out of range\n",
      "7493\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10708.png'>\n",
      "10708\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3627.png'>\n",
      "3627\n",
      "tuple index out of range\n",
      "5634\n",
      "tuple index out of range\n",
      "9769\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7080.png'>\n",
      "7080\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (8 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "2311\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8922.png'>\n",
      "8922\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3982.png'>\n",
      "3982\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5776.png'>\n",
      "5776\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8569.png'>\n",
      "8569\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2456.png'>\n",
      "2456\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9959.png'>\n",
      "9959\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9970.png'>\n",
      "9970\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3439.png'>\n",
      "3439\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1297.png'>\n",
      "1297\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6459.png'>\n",
      "6459\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10755.png'>\n",
      "10755\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11025.png'>\n",
      "11025\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_5605.png'>\n",
      "5605\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6646.png'>\n",
      "6646\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3387.png'>\n",
      "3387\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7667.png'>\n",
      "7667\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_742.png'>\n",
      "742\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10969.png'>\n",
      "10969\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8816.png'>\n",
      "8816\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10157.png'>\n",
      "10157\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9193.png'>\n",
      "9193\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8205.png'>\n",
      "8205\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6698.png'>\n",
      "6698\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6334.png'>\n",
      "6334\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "7228\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12225.png'>\n",
      "12225\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2282.png'>\n",
      "2282\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10781.png'>\n",
      "10781\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1419.png'>\n",
      "1419\n",
      "Could not load \"\" \n",
      "Reason: \"image file is truncated (4 bytes not processed)\"\n",
      "Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries\n",
      "7519\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2169.png'>\n",
      "2169\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3820.png'>\n",
      "3820\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4959.png'>\n",
      "4959\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "10410\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3817.png'>\n",
      "3817\n",
      "tuple index out of range\n",
      "31\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7876.png'>\n",
      "7876\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_129.png'>\n",
      "129\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_317.png'>\n",
      "317\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4887.png'>\n",
      "4887\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9796.png'>\n",
      "9796\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2318.png'>\n",
      "2318\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2026.png'>\n",
      "2026\n",
      "tuple index out of range\n",
      "4582\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12439.png'>\n",
      "12439\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_2490.png'>\n",
      "2490\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3094.png'>\n",
      "3094\n",
      "tuple index out of range\n",
      "722\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4735.png'>\n",
      "4735\n",
      "tuple index out of range\n",
      "12328\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9446.png'>\n",
      "9446\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9262.png'>\n",
      "9262\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10835.png'>\n",
      "10835\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_10974.png'>\n",
      "10974\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6700.png'>\n",
      "6700\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11145.png'>\n",
      "11145\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_733.png'>\n",
      "733\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_721.png'>\n",
      "721\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11898.png'>\n",
      "11898\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "11714\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4190.png'>\n",
      "4190\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_6398.png'>\n",
      "6398\n",
      "Only 2-D images (grayscale or color) are supported, when providing a callable `inverse_map`.\n",
      "313\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_9981.png'>\n",
      "9981\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_3969.png'>\n",
      "3969\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11088.png'>\n",
      "11088\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_8846.png'>\n",
      "8846\n",
      "tuple index out of range\n",
      "7673\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_42.png'>\n",
      "42\n",
      "tuple index out of range\n",
      "11852\n",
      "tuple index out of range\n",
      "9918\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_11633.png'>\n",
      "11633\n",
      "tuple index out of range\n",
      "4926\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_593.png'>\n",
      "593\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_571.png'>\n",
      "571\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_12012.png'>\n",
      "12012\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_4075.png'>\n",
      "4075\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_7552.png'>\n",
      "7552\n",
      "cannot identify image file <_io.BufferedReader name='../data/test/pic_1298.png'>\n",
      "1298\n"
     ]
    }
   ],
   "source": [
    "test_images_list = load_images('../data/test', (299, 299))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "test_image_array = np.array(\n",
    "    [image[1] \n",
    "     for image in test_images_list\n",
    "     if image[1].shape[2] == 3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "test_predictions = [\n",
    "    [x[0], transfer_model.predict(x[1].reshape([1, 299, 299, 3]))] \n",
    "    for x in test_images_list \n",
    "    if (len(x[1].shape) == 3 and x[1].shape[2] == 3)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "test_predictions_dict = dict([[int(x[0]), x[1]] for x in test_predictions])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "26"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "list(test_predictions_dict.items())[0][1].argmax() + 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_or_1(x):\n",
    "    return test_predictions_dict[x].argmax() if x in test_predictions_dict.keys() else 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = pd.DataFrame([[i, predict_or_1(i)] for i in range(1, 12801)], columns=['id', 'predicted'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "results.to_csv('first-submission.csv', index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Legacy code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'model' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-6322a3d53043>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mintermediate_layer_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mModel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minputs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moutputs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlayers\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m311\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutput\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mintermediate_layer_model\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutput\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mDense\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1024\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'relu'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mpredictions\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mDense\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'softmax'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'model' is not defined"
     ]
    }
   ],
   "source": [
    "model = InceptionV3(weights='imagenet')\n",
    "\n",
    "intermediate_layer_model = Model(inputs=model.input, outputs=model.layers[311].output)\n",
    "\n",
    "x = intermediate_layer_model.output\n",
    "x = Dense(1024, activation='relu')(x)\n",
    "predictions = Dense(2, activation='softmax')(x)\n",
    "\n",
    "transfer_model = Model(inputs=intermediate_layer_model.input, outputs=predictions)\n",
    "\n",
    "# train last cluster and dense layer\n",
    "for layer in transfer_model.layers:\n",
    "    layer.trainable = False\n",
    "\n",
    "# can train more \n",
    "for i in range(311,313):\n",
    "    transfer_model.layers[i].trainable = True\n",
    "\n",
    "transfer_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "################### training last X layers ###################\n",
    "epoch = 20\n",
    "num_classes = 128\n",
    "# onehot encoding\n",
    "y_onehot = np.zeros((y_data.shape[0], num_classes))\n",
    "for i in range(0,num_classes):\n",
    "    (y_onehot[:,i:i+1])[y_data==i] = 1\n",
    "\n",
    "# using checkpoints and early stopping on validation sample to prevent overfitting\n",
    "# best weight is saved to file_path\n",
    "file_path=\".../weights_base.best.hdf5\"\n",
    "checkpoint = ModelCheckpoint(file_path, monitor='val_loss', verbose=1, save_best_only=True, mode='min')\n",
    "early = EarlyStopping(monitor=\"val_loss\", mode=\"min\", patience=2)\n",
    "callbacks_list = [checkpoint, early] \n",
    "\n",
    "transfer_model.fit(x_data, y_onehot, epochs=epoch, validation_split=0.1, batch_size=32, callbacks=callbacks_list)\n",
    "\n",
    "# load best weights\n",
    "transfer_model.load_weights(file_path)\n",
    "\n",
    "# need prediction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.5/inception_v3_weights_tf_dim_ordering_tf_kernels.h5\n",
      "39952384/96112376 [===========>..................] - ETA: 17:04"
     ]
    }
   ],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
